window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/22224365-adc8a19e';
window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'http:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone'];window['___lcfg'] = {"gwidget":{"parsetags":"onload"},"rpc":{"commSwf":"//xpc.googleusercontent.com/gadgets","passReferrer":"p2c:query","parentRelayUrl":"/rpc_relay.html"},"iframes":{":socialhost:":"http://apis.google.com","profilecard":{"params":{"style":"#","m":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/appcard"},"plusone_m":{"params":{"count":"#","url":"#","size":"#"},"url":":socialhost:/u/:session_index:/_/+1/button"},"plusone":{"params":{"count":"#","url":"#","size":"#"},"url":":socialhost:/u/:session_index:/_/+1/button"}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"chili.entities.starred.insert":{"cache":{"invalidates":["chili.entities.starred","chili.entitiesDefaultAcl"]}},"chili.people.get":true,"chili.entities.get":true,"pos.plusones.delete":true,"chili.entities.starred.delete":true,"chili.entities.list":true,"pos.plusones.get":true,"chili.groups.list":true,"pos.plusones.getDefaultAcl":{"cache":{"enabled":true}},"chili.entities.starred.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"chili.entitiesDefaultAcl.get":true,"chili.entities.starred.list":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"proxy":"https://clients6.google.com/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","jsh":"r;gc/22224365-adc8a19e","auth":{"useInterimAuth":false}}};var jsloader=window.jsloader||{};
var gapi=window.gapi||{};
(function(){function k(){return window.___jsl=window.___jsl||{}}function n(b,c,e,a){e=p(e).join(b);a&&a.length>0&&(e+=c+p(a).join(b));return e}function r(b){for(var c={},e=0,a;a=b[e];e++)c[a]=1;return c}function p(b){var c=[],e;for(e in r(b))c.push(e);return c.sort()}function u(){var b;if((b=j.match(v))||(b=j.match(w)))try{return decodeURIComponent(b[2])}catch(c){return null}else return k().h}function l(b){m=g="";q={};i=[];h=window.console||window.opera&&window.opera.postError;j=b;if(b=u()){b=b.split(";");
g=b.shift();var c=g!=="s"&&g!=="r";m=c?b.shift():"https://ssl.gstatic.com/webclient/js";o=(c=g!=="s"&&g!=="i")&&b.shift();s=(c=g==="d")&&(b.shift()||"gcjs-3p");t=c&&b.shift()||"";if(c=g==="s"||g==="i")for(var c=0,e;e=b[c];c++){e=e.split("@");var a=q,d,f=e[0].split("!");d=f[0].split(":");f=f[1]&&f[1].split(":");d=n(":","!",d,f);a[d]=e[1]}}}var v=/\?([^&#]*&)*jsh=([^&#]*)/,w=/#([^&]*&)*jsh=([^&]*)/,x=/^https:\/\/ssl.gstatic.com\/webclient\/js(\/[a-zA-Z0-9_\-]+)*\/[a-zA-Z0-9_\-\.:!]+\.js$/,y=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?\//,
g,m,s,t,o,q,i,h,j;l(document.location.href);jsloader.load=function(b,c,e){var a;if(!b||b.length==0)h&&h.warn("Cannot load empty features.");else{var d;d=r(i);for(var f=!0,j=0,l;l=f&&b[j];j++)f=f&&d[l];(d=f)?(d="Cannot load loaded features ["+b.join(",")+"].",h&&h.warn(d)):g==="s"||g==="i"?(a=n(":","!",b,i),(d=q[a])?a=m+"/"+d+".js":(h&&h.warn("Cannot find features ["+a+"]."),a=void 0)):g==="d"?(a=m+"/"+n(":","!",b,i),a+=".js?container="+s+"&c=2&jsload=0",o&&(a+="&r="+o),t=="d"&&(a+="&debug=1")):g===
"r"||g==="f"?a=m+"/"+o+"/"+n("__","--",b,i)+".js":(d="Cannot respond for features ["+b.join(",")+"].",h&&h.warn(d))}d=c;c=e;if(a){if(e=d){if(k().c)throw"Cannot continue until a pending callback completes.";k().c=e;k().o=1}a=e=a;g==="s"||g==="r"?a=a.match(x):(d=a.match(y),(a=k().m)&&d?(d=d[2],f=d.lastIndexOf(a),a=(f==0||a.charAt(0)=="."||d.charAt(f-1)==".")&&d.length-a.length==f):a=!1);if(!a)throw"Cannot load url "+e+".";c=c||{};c=window.___gapisync||c.sync;if(typeof c=="undefined"){c=!1;a=document.getElementsByTagName("meta");
for(d=0;f=!c&&a[d];++d)"generator"==f.getAttribute("name")&&"blogger"==f.getAttribute("content")&&(c=!0)}c?document.write('<script src="'+e+'"><\/script>'):(c=document.createElement("script"),c.setAttribute("src",e),document.getElementsByTagName("head")[0].appendChild(c));i=p(i.concat(b))}else d&&d()};jsloader.reinitialize_=function(b){l(b)}})();
gapi.load=function(a,b){jsloader.load(a.split(":"),b)};
gapi.load('googleapis.client:plusone', window['__bsld'], null);